# Generated by Django 4.2.7 on 2023-12-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('titulolibro', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('cantante', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
            ],
        ),
    ]
